# Generated by Django 4.2.8 on 2023-12-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
