# Generated by Django 4.2.8 on 2023-12-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
